[package]
name = "zerolaunch-rs"
version = "0.4.0"
description = "A Tauri App"
authors = ["ghost-him"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "zerolaunch_rs_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "^2", features = [] }

[dependencies]
windows = { version = "^0.59.0", features = [
    "Win32_UI_WindowsAndMessaging",
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Management_Deployment",
    "Win32_System_Threading",
    "Foundation",
    "Win32_Security",
    "Foundation_Collections",
    "System",
    "Win32_System_Com",
    "Win32_System_Com_StructuredStorage",
    "Win32_UI_Shell",
    "Storage_Streams",
    "Win32_UI_Shell_PropertiesSystem",
    "Win32_System_Variant",
    "Win32_System_Registry",
    "Win32_Storage_FileSystem",
    "Win32_System_Console",
] }

tauri = { version = "^2", features = ["tray-icon", "image-ico", "image-png"] }
tauri-plugin-shell = "^2"
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
lazy_static = "^1.5.0"
rdev = { version = "^0.5.3", features = ["unstable_grab"] }
widestring = "^1.1.0"
windows-core = "^0.59.0"
rayon = "^1.10.0"
single-instance = "^0.3.3"
base64 = "^0.22.1"
dashmap = "^6.1.0"
image = "^0.25.5"
tracing = "^0.1.41"
tracing-subscriber = { version = "^0.3.19", features = ["env-filter"] }
tracing-appender = "^0.2.3"
chrono = "^0.4.39"
parking_lot = "^0.12.3"
tauri-plugin-global-shortcut = "^2.2.0"
tauri-plugin-dialog = { version = "^2.2.0" }
timer = "^0.2.0"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-autostart = "^2"
